import "./components/products.js";
import "./components/mouse.js";
import "./components/sliders.js";
import "./components/matter.js";
import "./components/cards.js";
import "./components/header.js";
import "./components/delivery.js";
import "./components/romb.js";
import "./components/aos.js";
import "./components/faq.js";
import "./components/plans.js";
import "./components/loyal-items.js";
import initLazyLoad from "./components/lazyImages.js";
